version: "3.9"
services:
  frontend:
    build:
      context: ./frontend/books
    env_file:
      - ./.env
    ports:
      - "8081:80"
  backend:
    build:
      context: ./backend/books
    env_file:
      - ./.env
    ports:
      - "8080:8080"
  db:
    image: postgres:12.9-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}

